=== GutManuel85/XmlJson/database/database_subjects.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="subject" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-id-subject">
            <xs:selector xpath="subject"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="subject">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="enrolledStudents" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="enrolledStudents">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-id-student">
            <xs:selector xpath="student"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="grade" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="grade">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="mark" type="markTyp" minOccurs="1" maxOccurs="1"/>
                <xs:element name="feedback" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="date" type="xs:date" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="markTyp">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="1.00"/>
            <xs:maxInclusive value="6.00"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== GutManuel85/XmlJson/database/database_subjects.xml
<?xml version="1.0"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database_subjects.xsd">
  <subject name="Mathematik">
    <enrolledStudents>
      <student id="3">
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-02-28">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
      </student>
      <student id="0">
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-02-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="1">
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-11">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="2">
        <grade date="2022-02-05">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="4">
        <grade date="2022-02-01">
          <mark>3</mark>
          <feedback>Ungen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
    </enrolledStudents>
  </subject>
  <subject name="Franz&#xF6;sisch">
    <enrolledStudents>
      <student id="0">
        <grade date="2022-02-02">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="1">
        <grade date="2022-02-02">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-07">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-09">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="4">
        <grade date="2022-03-14">
          <mark>3</mark>
          <feedback>Ungen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-12">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="2">
        <grade date="2022-02-05">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-07">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
        <grade date="2022-03-01">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
    </enrolledStudents>
  </subject>
  <subject name="Italienisch">
    <enrolledStudents>
      <student id="3">
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
      </student>
      <student id="2">
        <grade date="2022-02-05">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
      </student>
    </enrolledStudents>
  </subject>
  <subject name="Gymnastik">
    <enrolledStudents>
      <student id="3">
        <grade date="2022-02-01">
          <mark>3.5</mark>
          <feedback>Ungen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
      </student>
      <student id="0">
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-11">
          <mark>5</mark>
          <feedback>gut</feedback>
        </grade>
        <grade date="2022-03-10">
          <mark>6</mark>
          <feedback>super</feedback>
        </grade>
      </student>
      <student id="2">
        <grade date="2022-02-05">
          <mark>5.5</mark>
          <feedback>Sehr gut</feedback>
        </grade>
      </student>
      <student id="4">
        <grade date="2022-03-07">
          <mark>6</mark>
          <feedback>Hervorragend</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
      </student>
    </enrolledStudents>
  </subject>
  <subject name="Zeichnen">
    <enrolledStudents>
      <student id="3">
        <grade date="2022-03-13">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-12">
          <mark>5</mark>
          <feedback>gut</feedback>
        </grade>
      </student>
      <student id="2">
        <grade date="2022-02-05">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
      </student>
      <student id="0">
        <grade date="2022-02-02">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
        <grade date="2022-03-14">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>4.5</mark>
          <feedback>Gen&#xFC;gend bis gut</feedback>
        </grade>
      </student>
      <student id="1">
        <grade date="2022-03-14">
          <mark>3</mark>
          <feedback>Ungen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-16">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
      </student>
      <student id="4">
        <grade date="2022-03-14">
          <mark>3</mark>
          <feedback>Ungen&#xFC;gend</feedback>
        </grade>
        <grade date="2022-03-13">
          <mark>5</mark>
          <feedback>Gut</feedback>
        </grade>
        <grade date="2022-03-15">
          <mark>4</mark>
          <feedback>Gen&#xFC;gend</feedback>
        </grade>
      </student>
    </enrolledStudents>
  </subject>
</school>
