=== GutManuel85/XmlJson/database/database_students.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="school">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="student" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="unique-id">
            <xs:selector xpath="student"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="firstName" type="xs:string"/>
                <xs:element name="lastName" type="xs:string"/>
                <xs:element name="birthDate" type="xs:date"/>
                <xs:element name="gender" type="genderTyp"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="genderTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Male"/>
            <xs:enumeration value="Female"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== GutManuel85/XmlJson/database/database_students.xml
<?xml version="1.0"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database_students.xsd">
  <student id="0">
    <firstName>Davide</firstName>
    <lastName>Ganci</lastName>
    <birthDate>1994-11-11</birthDate>
    <gender>Male</gender>
  </student>
  <student id="1">
    <firstName>Manuel</firstName>
    <lastName>Gut</lastName>
    <birthDate>232021-05-23</birthDate>
    <gender>Male</gender>
  </student>
  <student id="2">
    <firstName>Monika</firstName>
    <lastName>Lehmann</lastName>
    <birthDate>2018-02-21</birthDate>
    <gender>Female</gender>
  </student>
  <student id="3">
    <firstName>Manuela</firstName>
    <lastName>Barthold</lastName>
    <birthDate>2022-01-04</birthDate>
    <gender>Female</gender>
  </student>
  <student id="4">
    <firstName>Philippe</firstName>
    <lastName>Mosaic</lastName>
    <birthDate>2021-09-28</birthDate>
    <gender>Male</gender>
  </student>
  <student id="5">
    <firstName>wert</firstName>
    <lastName>wert</lastName>
    <birthDate>2022-03-11</birthDate>
    <gender>Female</gender>
  </student>
</school>
